[package]
name = "bbtest"
version = "0.1.0"
authors = ["doomy <2640792-_doomy@users.noreply.gitlab.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
big-brain = "0.6.0"
bevy = "0.5"
rand = "0.8"